// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_segment_sources {
};

export interface SegmentSource {
  id: string;
  name: string;
  slug: string;
  enabled: boolean;
  sourceId: string;
  workspaceId: string;
  metadata: {  id: string;
  name: string;
  slug?: string | undefined;
  description?: string | undefined;
  website?: string | undefined;
  categories?: string[] | undefined;
  options?: {  [key: string]: any | undefined;};};
  settings?: {  [key: string]: any | undefined;};
  createdAt: string;
  updatedAt: string;
};

export interface SyncMetadata_segment_destinations {
};

export interface SegmentDestination {
  id: string;
  name: string;
  enabled: boolean;
  connectionMode?: string | undefined;
  destinationDefinitionId: string;
  sourceId: string;
  workspaceId: string;
  metadata: {  id: string;
  name: string;
  slug?: string | undefined;
  description?: string | undefined;
  website?: string | undefined;
  categories?: string[] | undefined;
  options?: {  [key: string]: any | undefined;};};
  settings?: {  [key: string]: any | undefined;};
  createdAt: string;
  updatedAt: string;
};

export interface SyncMetadata_segment_subscriptions {
};

export interface SegmentSubscription {
  id: string;
  name: string;
  actionId: string;
  actionSlug?: string | undefined;
  destinationId: string;
  enabled: boolean;
  trigger: string;
  settings?: {  subscriptionId?: string | undefined;
  type?: string | undefined;
  trigger?: string | undefined;
  actions?: {  [key: string]: any | undefined;};
  fields?: {  [key: string]: any | undefined;};};
  createdAt: string;
  updatedAt: string;
};

export interface SyncMetadata_segment_workspace {
};

export interface SegmentWorkspace {
  id: string;
  name: string;
  slug: string;
  createdAt: string;
  updatedAt: string;
};
