// ---------------------------
// This file was generated by Nango (v0.69.13)
// You can version this file
// ---------------------------

export interface ActionInput_google_drive_foldercontent {
  id?: string | undefined;
  cursor?: string | undefined;
};

export interface ActionOutput_google_drive_foldercontent {
  files: ({  id: string;
  name: string;
  mimeType: string;
  parents: string[];
  modifiedTime?: string | undefined;
  createdTime?: string | undefined;
  webViewLink?: string | undefined;
  kind?: string | undefined;})[];
  folders: ({  id: string;
  name: string;
  mimeType: string;
  parents: string[];
  modifiedTime?: string | undefined;
  createdTime?: string | undefined;
  webViewLink?: string | undefined;
  kind?: string | undefined;})[];
  next_cursor?: string | undefined;
};

export interface ActionInput_google_drive_uploaddocument {
  content: string;
  name: string;
  mimeType: string;
  folderId?: string | undefined;
  description?: string | undefined;
  isBase64?: boolean | undefined;
};

export interface ActionOutput_google_drive_uploaddocument {
  id: string;
  name: string;
  mimeType: string;
  parents: string[];
  modifiedTime?: string | undefined;
  createdTime?: string | undefined;
  webViewLink?: string | undefined;
  kind?: string | undefined;
};

export interface ActionInput_google_drive_listdrives {
  cursor: string;
};

export interface ActionOutput_google_drive_listdrives {
  drives: ({  id: string;
  name: string;
  kind: string;
  createdTime: string;
  hidden: boolean;
  capabilities: {  canAddChildren: boolean;
  canComment: boolean;
  canCopy: boolean;
  canDeleteDrive: boolean;
  canDownload: boolean;
  canEdit: boolean;
  canListChildren: boolean;
  canManageMembers: boolean;
  canReadRevisions: boolean;
  canRename: boolean;
  canShare: boolean;
  canTrashChildren: boolean;
  canRenameDrive: boolean;
  canChangeDriveBackground: boolean;
  canChangeCopyRequiresWriterPermissionRestriction: boolean;
  canChangeDomainUsersOnlyRestriction: boolean;
  canChangeDriveMembersOnlyRestriction: boolean;
  canChangeSharingFoldersRequiresOrganizerPermissionRestriction: boolean;
  canResetDriveRestrictions: boolean;
  canDeleteChildren: boolean;};
  restrictions: {  adminManagedRestrictions: boolean;
  copyRequiresWriterPermission: boolean;
  domainUsersOnly: boolean;
  driveMembersOnly: boolean;
  sharingFoldersRequiresPublisherPermission: boolean;
  sharingFoldersRequiresOrganizerPermission: boolean;};})[];
  next_cursor: string;
  kind: string;
};

export interface ActionInput_google_drive_fetchfolders {
  parentId?: string | undefined;
  limit?: number | undefined;
  recursive?: boolean | undefined;
  query?: string | undefined;
};

export interface ActionOutput_google_drive_fetchfolders {
  folders: ({  id: string;
  url: string;
  title: string;
  mimeType: string;
  updatedAt: string;})[];
};

export interface ActionInput_google_drive_fetchdocuments {
  files?: string[] | undefined;
  folders?: string[] | undefined;
  mimeType?: string | undefined;
  limit?: number | undefined;
  includeSubfolders?: boolean | undefined;
  query?: string | undefined;
};

export interface ActionOutput_google_drive_fetchdocuments {
  documents: ({  id: string;
  url: string;
  title: string;
  mimeType: string;
  updatedAt: string;})[];
};
