// ---------------------------
// This file was generated by Nango (v0.69.13)
// You can version this file
// ---------------------------

export type ActionInput_hubspot_whoami = void

export interface ActionOutput_hubspot_whoami {
  id: number;
  email: string;
};

export interface ActionInput_hubspot_fetchproperties {
  name: string;
};

export interface ActionOutput_hubspot_fetchproperties {
  results: ({  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  name: string;
  label: string;
  type: string;
  fieldType: string;
  description: string;
  groupName: string;
  options: any[];
  displayOrder: number;
  calculated: boolean;
  externalOptions: boolean;
  hasUniqueValue: boolean;
  hidden: boolean;
  hubspotDefined?: boolean | undefined;
  showCurrencySymbol?: boolean | undefined;
  modificationMetadata?: {  archivable?: boolean | undefined;
  readOnlyDefinition?: boolean | undefined;
  readOnlyValue?: boolean | undefined;
  readOnlyOptions?: boolean | undefined;};
  formField: boolean;
  dataSensitivity: string;})[];
};

export interface ActionInput_hubspot_createproperty {
  objectType: string;
  data: {  hidden?: boolean | undefined;
  displayOrder?: number | undefined;
  description?: string | undefined;
  label: string;
  type: string;
  formField?: boolean | undefined;
  groupName: string;
  referencedObjectType?: string | undefined;
  name: string;
  options: ({  hidden: boolean;
  displayOrder?: number | undefined;
  description?: string | undefined;
  label: string;
  value: string;})[];
  calculationFormula?: string | undefined;
  hasUniqueValue?: boolean | undefined;
  fieldType: string;
  externalOptions?: boolean | undefined;};
};

export interface ActionOutput_hubspot_createproperty {
  createdUserId: string;
  hidden: boolean;
  modificationMetadata: {  readOnlyOptions?: boolean | undefined;
  readOnlyValue: boolean;
  readOnlyDefinition: boolean;
  archivable: boolean;};
  displayOrder: number;
  description: string;
  showCurrencySymbol?: boolean | undefined;
  label: string;
  type: string;
  hubspotDefined?: boolean | undefined;
  formField: boolean;
  dataSensitivity?: string | undefined;
  createdAt: string;
  archivedAt?: string | undefined;
  archived: boolean;
  groupName: string;
  referencedObjectType?: string | undefined;
  name: string;
  options: ({  hidden: boolean;
  displayOrder: number;
  description: string;
  label: string;
  value: string;})[];
  calculationFormula?: string | undefined;
  hasUniqueValue: boolean;
  fieldType: string;
  updatedUserId: string;
  calculated: boolean;
  externalOptions: boolean;
  updatedAt: string;
};

export interface ActionInput_hubspot_createdeal {
  name?: string | undefined;
  amount?: string | undefined;
  close_date?: string | undefined;
  deal_description?: string | undefined;
  owner?: string | undefined;
  deal_stage?: string | undefined;
  deal_probability?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionOutput_hubspot_createdeal {
  id: string;
  name?: string | undefined;
  amount?: string | undefined;
  close_date?: string | undefined;
  deal_description?: string | undefined;
  owner?: string | undefined;
  deal_stage?: string | undefined;
  deal_probability?: string | undefined;
};

export interface ActionInput_hubspot_updatedeal {
  id: string;
  name?: string | undefined;
  amount?: string | undefined;
  close_date?: string | undefined;
  deal_description?: string | undefined;
  owner?: string | undefined;
  deal_stage?: string | undefined;
  deal_probability?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionOutput_hubspot_updatedeal {
  id: string;
  name?: string | undefined;
  amount?: string | undefined;
  close_date?: string | undefined;
  deal_description?: string | undefined;
  owner?: string | undefined;
  deal_stage?: string | undefined;
  deal_probability?: string | undefined;
};

export interface ActionInput_hubspot_deletedeal {
  id: string;
};

export interface ActionOutput_hubspot_deletedeal {
  success: boolean;
};

export interface ActionInput_hubspot_fetchpipelines {
  objectType?: string | undefined;
};

export interface ActionOutput_hubspot_fetchpipelines {
  pipelines: ({  updatedAt: string;
  createdAt: string;
  label: string;
  displayOrder: number;
  id: string;
  archived: boolean;
  stages: ({  updatedAt: string;
  createdAt: string;
  label: string;
  displayOrder: number;
  metadata: {  isClosed: boolean;
  probability: string;};
  id: string;
  archived: boolean;
  writePermissions: string;})[];})[];
};

export interface ActionInput_hubspot_createuser {
  firstName?: string | undefined;
  lastName?: string | undefined;
  primaryTeamId?: string | undefined;
  email: string;
  sendWelcomeEmail?: boolean | undefined;
  roleId?: string | undefined;
  secondaryTeamIds: string[];
};

export interface ActionOutput_hubspot_createuser {
  id: string;
  firstName: string;
  lastName: string;
  primaryTeamId?: string | undefined;
  email: string;
  sendWelcomeEmail: boolean;
  roleIds: string[];
  secondaryTeamIds: string[];
  superAdmin: boolean;
};

export interface ActionInput_hubspot_deleteuser {
  id: string;
};

export interface ActionOutput_hubspot_deleteuser {
  success: boolean;
};

export type ActionInput_hubspot_fetchroles = void

export interface ActionOutput_hubspot_fetchroles {
  results: ({  requiresBillingWrite: boolean;
  name: string;
  id: string;})[];
};

export interface ActionInput_hubspot_changeuserrole {
  id: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  primaryTeamId?: string | undefined;
};

export interface ActionOutput_hubspot_changeuserrole {
  id: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  primaryTeamId?: string | undefined;
  email: string;
  sendWelcomeEmail?: boolean | undefined;
  roleIds: string[];
  secondaryTeamIds: string[];
  superAdmin: boolean;
};

export type ActionInput_hubspot_fetchaccountinformation = void

export interface ActionOutput_hubspot_fetchaccountinformation {
  id: string;
  type: string;
  timeZone: string;
  companyCurrency: string;
  additionalCurrencies: string[];
  utcOffset: string;
  utcOffsetMilliseconds: number;
  uiDomain: string;
  dataHostingLocation: string;
};

export type ActionInput_hubspot_fetchcustomobjects = void

export interface ActionOutput_hubspot_fetchcustomobjects {
  id: string;
};

export interface ActionInput_hubspot_createcontact {
  first_name?: string | undefined;
  last_name?: string | undefined;
  email?: string | undefined;
  job_title?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  salutation?: string | undefined;
  mobile_phone_number?: string | undefined;
  website_url?: string | undefined;
  owner?: string | undefined;
};

export interface ActionOutput_hubspot_createcontact {
  id: string;
  created_date: string;
  first_name?: string | undefined;
  last_name?: string | undefined;
  email?: string | undefined;
  job_title?: string | undefined;
  last_contacted?: string | undefined;
  last_activity_date?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  salutation?: string | undefined;
  mobile_phone_number?: string | undefined;
  website_url?: string | undefined;
  owner?: string | undefined;
};

export interface ActionInput_hubspot_updatecontact {
  first_name?: string | undefined;
  last_name?: string | undefined;
  email?: string | undefined;
  job_title?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  salutation?: string | undefined;
  mobile_phone_number?: string | undefined;
  website_url?: string | undefined;
  owner?: string | undefined;
  id: string;
};

export interface ActionOutput_hubspot_updatecontact {
  id: string;
  created_date: string;
  first_name?: string | undefined;
  last_name?: string | undefined;
  email?: string | undefined;
  job_title?: string | undefined;
  last_contacted?: string | undefined;
  last_activity_date?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  salutation?: string | undefined;
  mobile_phone_number?: string | undefined;
  website_url?: string | undefined;
  owner?: string | undefined;
};

export interface ActionInput_hubspot_deletecontact {
  id: string;
};

export interface ActionOutput_hubspot_deletecontact {
  success: boolean;
};

export interface ActionInput_hubspot_createcompany {
  name?: string | undefined;
  industry?: string | undefined;
  description?: string | undefined;
  country?: string | undefined;
  city?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  owner?: string | undefined;
  year_founded?: string | undefined;
  website_url?: string | undefined;
};

export interface ActionOutput_hubspot_createcompany {
  id: string;
  created_date: string;
  name?: string | undefined;
  industry?: string | undefined;
  description?: string | undefined;
  country?: string | undefined;
  city?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  owner?: string | undefined;
  year_founded?: string | undefined;
  website_url?: string | undefined;
};

export interface ActionInput_hubspot_updatecompany {
  id: string;
  name?: string | undefined;
  industry?: string | undefined;
  description?: string | undefined;
  country?: string | undefined;
  city?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  owner?: string | undefined;
  year_founded?: string | undefined;
  website_url?: string | undefined;
};

export interface ActionOutput_hubspot_updatecompany {
  id: string;
  created_date: string;
  name?: string | undefined;
  industry?: string | undefined;
  description?: string | undefined;
  country?: string | undefined;
  city?: string | undefined;
  lead_status?: string | undefined;
  lifecycle_stage?: string | undefined;
  owner?: string | undefined;
  year_founded?: string | undefined;
  website_url?: string | undefined;
};

export interface ActionInput_hubspot_deletecompany {
  id: string;
};

export interface ActionOutput_hubspot_deletecompany {
  success: boolean;
};

export interface ActionInput_hubspot_createtask {
  task_type?: string | undefined;
  title?: string | undefined;
  priority?: string | undefined;
  assigned_to?: string | undefined;
  due_date?: string | undefined;
  notes?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionOutput_hubspot_createtask {
  id: string;
  task_type?: string | undefined;
  title?: string | undefined;
  priority?: string | undefined;
  assigned_to?: string | undefined;
  due_date?: string | undefined;
  notes?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionInput_hubspot_updatetask {
  id: string;
  task_type?: string | undefined;
  title?: string | undefined;
  priority?: string | undefined;
  assigned_to?: string | undefined;
  due_date?: string | undefined;
  notes?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionOutput_hubspot_updatetask {
  id: string;
  task_type?: string | undefined;
  title?: string | undefined;
  priority?: string | undefined;
  assigned_to?: string | undefined;
  due_date?: string | undefined;
  notes?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionInput_hubspot_deletetask {
  id: string;
};

export interface ActionOutput_hubspot_deletetask {
  success: boolean;
};

export interface ActionInput_hubspot_createnote {
  id?: string | undefined;
  time_stamp: string;
  created_date?: string | undefined;
  body?: string | undefined;
  attachment_ids?: string | undefined;
  owner?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionOutput_hubspot_createnote {
  id?: string | undefined;
  time_stamp: string;
  created_date?: string | undefined;
  body?: string | undefined;
  attachment_ids?: string | undefined;
  owner?: string | undefined;
  associations?: ({  to: number;
  types: ({  association_category: string;
  association_type_Id: number;})[];})[] | undefined;
};

export interface ActionInput_hubspot_fetchcompanies {
  limit?: number | undefined;
  properties?: string[] | undefined;
};

export interface ActionOutput_hubspot_fetchcompanies {
  companies: ({  id: string;
  created_date: string | null;
  name: string | null;
  industry: string | null;
  description: string | null;
  country: string | null;
  city: string | null;
  lead_status: string | null;
  lifecycle_stage: string | null;
  owner: string | null;
  year_founded: string | null;
  website_url: string | null;})[];
};

export interface ActionInput_hubspot_fetchcontacts {
  limit?: number | undefined;
  properties?: string[] | undefined;
};

export interface ActionOutput_hubspot_fetchcontacts {
  contacts: ({  id: string;
  created_date: string;
  first_name: string | null;
  last_name: string | null;
  email: string | null;
  job_title: string | null;
  last_contacted: string | null;
  last_activity_date: string | null;
  lead_status: string | null;
  lifecycle_stage: string | null;
  salutation: string | null;
  mobile_phone_number: string | null;
  website_url: string | null;
  owner: string | null;})[];
};

export type ActionInput_hubspot_fetchcurrencycodes = void

export interface ActionOutput_hubspot_fetchcurrencycodes {
  currencyCodes: ({  id: string;
  code: string;
  description: string;})[];
};

export interface ActionInput_hubspot_fetchdeals {
  limit?: number | undefined;
  properties?: string[] | undefined;
  includeAssociations?: boolean | undefined;
};

export interface ActionOutput_hubspot_fetchdeals {
  deals: ({  id: string;
  name: string | null;
  amount: string | null;
  close_date: string | null;
  deal_description: string | null;
  owner: string | null;
  deal_stage: string | null;
  deal_probability: string | null;
  returned_associations?: {  companies?: ({  id: string;
  name: string | null;})[] | undefined;
  contacts?: ({  id: string;
  first_name: string | null;
  last_name: string | null;})[] | undefined;
  deals?: ({  id: string;
  name: string | null;})[] | undefined;};})[];
};

export interface ActionInput_hubspot_fetchknowledgebase {
  limit?: number | undefined;
  term?: string | undefined;
};

export interface ActionOutput_hubspot_fetchknowledgebase {
  knowledgeBase: ({  id: string;
  title: string;
  description: string;
  category: string;
  content: string;
  publishDate: number;})[];
};

export interface ActionInput_hubspot_fetchowners {
  limit?: number | undefined;
};

export interface ActionOutput_hubspot_fetchowners {
  owners: ({  id: string;
  email: string;
  firstName: string;
  lastName: string;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
  archived: boolean;})[];
};

export interface ActionInput_hubspot_fetchproducts {
  limit?: number | undefined;
  properties?: string[] | undefined;
};

export interface ActionOutput_hubspot_fetchproducts {
  products: ({  updatedAt: string;
  createdAt: string;
  id: string;
  amount: number | null;
  description: string | null;
  discount: number | null;
  sku: string | null;
  url: string | null;
  name: string;
  price: string;
  quantity: number | null;
  recurringBillingFrequency: number | null;
  tax: null | number;})[];
};

export interface ActionInput_hubspot_fetchservicetickets {
  limit?: number | undefined;
  properties?: string[] | undefined;
  modifiedSince?: string | undefined;
};

export interface ActionOutput_hubspot_fetchservicetickets {
  serviceTickets: ({  id: string;
  createdAt: Date;
  updatedAt: Date;
  isArchived: boolean;
  subject: string;
  content: string;
  objectId: number;
  ownerId: number;
  pipeline: number;
  pipelineStage: number;
  ticketCategory: string | null;
  ticketPriority: string;})[];
};
